# Generated by Django 4.1.2 on 2022-11-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportcrud',
            name='video',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
