# Generated by Django 4.1.2 on 2022-11-01 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('sportcrud', '0002_alter_sportcrud_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportcrud',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SportCrud', to='category.category'),
        ),
    ]
