# Generated by Django 4.1.2 on 2022-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('group_blood', models.CharField(blank=True, max_length=10)),
                ('allergy', models.CharField(blank=True, max_length=100)),
                ('symptoms', models.CharField(blank=True, max_length=500)),
                ('disability', models.CharField(max_length=100)),
                ('illness', models.CharField(max_length=100)),
            ],
        ),
    ]
