# Generated by Django 4.1.2 on 2022-10-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='injury',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='injury_images',
            field=models.ImageField(blank=True, upload_to='injury_images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='person_images',
            field=models.ImageField(blank=True, upload_to='person_image/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='disability',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
