# Generated by Django 4.1.2 on 2022-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_person_injury_person_injury_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(max_length=100, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='allergy',
            field=models.CharField(blank=True, max_length=100, verbose_name='аллергия на что либо'),
        ),
        migrations.AlterField(
            model_name='person',
            name='disability',
            field=models.CharField(blank=True, max_length=100, verbose_name='инвалидность'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group_blood',
            field=models.CharField(blank=True, max_length=10, verbose_name='группа крови'),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.CharField(blank=True, max_length=10, verbose_name='выстота'),
        ),
        migrations.AlterField(
            model_name='person',
            name='illness',
            field=models.CharField(max_length=100, verbose_name='болезнь'),
        ),
        migrations.AlterField(
            model_name='person',
            name='injury',
            field=models.CharField(blank=True, max_length=100, verbose_name='травма'),
        ),
        migrations.AlterField(
            model_name='person',
            name='injury_images',
            field=models.ImageField(blank=True, upload_to='injury_images/', verbose_name='фотография травмы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_images',
            field=models.ImageField(blank=True, upload_to='person_image/', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='person',
            name='symptoms',
            field=models.CharField(blank=True, max_length=500, verbose_name='симптомы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.CharField(blank=True, max_length=100, verbose_name='вес'),
        ),
    ]
