# Generated by Django 4.1.2 on 2022-11-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_person_age_alter_person_allergy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='group_blood',
            new_name='blood_type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='injury_images',
        ),
    ]
